### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uservoice.uservoicesdk.activity.ArticleActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by BurningBird** [uservoice/uservoice-android-sdk#103]
Crashed Thread
0	
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uservoice.uservoicesdk.activity.ArticleActivity}: java.lang.NullPointerException
1	
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2119)
2	
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
3	
at android.app.ActivityThread.access$600(ActivityThread.java:131)
4	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
5	
at android.os.Handler.dispatchMessage(Handler.java:99)
6	
at android.os.Looper.loop(Looper.java:137)
7	
at android.app.ActivityThread.main(ActivityThread.java:4821)
8	
at java.lang.reflect.Method.invokeNative(Native Method)
9	
at java.lang.reflect.Method.invoke(Method.java:511)
10	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12	
at dalvik.system.NativeStart.main(Native Method)
13	
Caused by: java.lang.NullPointerException
14	
at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:29)
15	
at android.app.Activity.performCreate(Activity.java:5163)
16	
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
17	
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2065)
18	
... 11 more
19	
java.lang.NullPointerException
20	
at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:29)
21	
at android.app.Activity.performCreate(Activity.java:5163)
22	
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
23	
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2065)
24	
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
25	
at android.app.ActivityThread.access$600(ActivityThread.java:131)
26	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
27	
at android.os.Handler.dispatchMessage(Handler.java:99)
28	
at android.os.Looper.loop(Looper.java:137)
29	
at android.app.ActivityThread.main(ActivityThread.java:4821)
30	
at java.lang.reflect.Method.invokeNative(Native Method)
31	
at java.lang.reflect.Method.invoke(Method.java:511)
32	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
33	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
34	
at dalvik.system.NativeStart.main(Native Method)

**Comment by austintaylor** [comment]
I believe this was fixed by 03f4ee0ba

**Comment by martyglaubitz** [comment]
still getting this crash in our production app (using sdk version 1.2.5)

_java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app/com.uservoice.uservoicesdk.activity.ArticleActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:5187)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
	... 11 more_
