### ISSUE TITLE
Unable to start activity ComponentInfo (NPE)

### ISSUE THREAD

**Issue by Dream-of-Electric-Sheep** [uservoice/uservoice-android-sdk#92]
Here's the stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dream_of_electric_sheep.android.m_parking/com.uservoice.uservoicesdk.activity.ArticleActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1959)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1984)
at android.app.ActivityThread.access$600(ActivityThread.java:126)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1150)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4456)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:29)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1923)
... 11 more
java.lang.NullPointerException
at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:29)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1923)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1984)
at android.app.ActivityThread.access$600(ActivityThread.java:126)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1150)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4456)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
at dalvik.system.NativeStart.main(Native Method)
```

UV Android SDK v1.0.

Unfortunately, can't provide more info :(

**Comment by austintaylor** [comment]
I believe this was fixed by 03f4ee0ba

**Comment by martyglaubitz** [comment]
We're still getting similar crashes. In fact, the same crash just with a different linenumber.
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{yo.whazzup/com.uservoice.uservoicesdk.activity.ArticleActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.uservoice.uservoicesdk.activity.ArticleActivity.onCreate(ArticleActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:5187)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
	... 11 more
```
i think this issue should be reopened
